
- name: Place rc script
  copy: src=php-fpm/php7_fpm dest=/usr/local/etc/rc.d/php7_fpm mode="u=rwx,g=rx,o=rx"
  sudo: yes
  tags:
    - php7
    - php-fpm

- name: Place fpm configuration file
  copy: src=php-fpm/php-fpm.conf dest=/home/vagrant/php7/etc/php-fpm.conf
  notify:
    - Restart php7_fpm
  tags:
    - php7
    - php-fpm

- name: Place pool configuration file
  copy: src=php-fpm/www.conf dest=/home/vagrant/php7/etc/php-fpm.d/www.conf
  notify:
    - Restart php7_fpm
  tags:
    - php7
    - php-fpm

- name: Be sure service php7_fpm enabled and started
  service: name=php7_fpm enabled=yes state=started
  sudo: yes
  tags:
    - php7
    - php-fpm

- name: Place nginx configuration file
  copy: src=nginx/nginx.conf dest=/usr/local/etc/nginx/
  sudo: yes
  notify:
    - Restart nginx
  tags:
    - php7
    - php-fpm

- name: Place script file
  copy: src={{ item }} dest=/usr/local/www/html/
  sudo: yes
  tags:
    - php7
    - php-fpm
  with_items:
    - www/index.php
    - www/bench.php
