
- name: Be sure installed redis
  pkgng: name=redis state=present
  sudo: yes
  tags: redis

- name: Be sure service redis enabled and started
  service: name=redis enabled=yes state=started
  sudo: yes
  tags: redis
