
- name: Update apt-cache
  apt: update_cache=yes
  sudo: yes
  tags: all

- name: Be sure installed zsh
  apt: name=zsh state=present
  sudo: yes
  tags: shell

- name: Change default shell
  user: name={{ ansible_user_id }} shell=/bin/zsh
  sudo: yes
  tags: shell

- name: Set shellrc file
  copy: src=.zshrc dest={{ ansible_env.HOME }}/
  tags: shell

- name: Set shellprofile file
  copy: src=.zshprofile dest={{ ansible_env.HOME }}/
  tags: shell

- name: Be sure installed python3
  apt: name=python3,python3-setuptools state=present
  sudo: yes
  tags: python

- name: Be sure installed pip
  easy_install: name=pip executable=easy_install-3.4
  sudo: yes
  tags: python

- include: swap.yml
