
- name: Be sure build dir
  file: path={{ ansible_env.HOME }}/php5 state=directory
  register: build_dir
  tags: php5

- name: Download PHP
  get_url: url=http://jp1.php.net/get/{{ php5_version }}.tar.bz2/from/this/mirror
    dest={{ build_dir.path }}/{{ php5_version }}.tar.bz2
  tags: php5

- name: Unpack tarball
  unarchive: src={{ build_dir.path }}/{{ php5_version }}.tar.bz2 dest={{ build_dir.path }}/ copy=no
  tags: php5

- name: Configure PHP
  command: >
    ./configure
    --prefix={{ build_dir.path }}
    --enable-fpm
    --enable-mbstring
    --enable-zip
    --enable-bcmath
    --enable-pcntl
    --enable-ftp
    --enable-exif
    --enable-calendar
    --enable-sysvmsg
    --enable-sysvsem
    --enable-sysvshm
    --enable-wddx
    --with-curl
    --with-mcrypt
    --with-iconv
    --with-gmp
    --with-pspell
    --with-gd
    --with-jpeg-dir=/usr
    --with-png-dir=/usr
    --with-zlib-dir=/usr
    --with-xpm-dir=/usr
    --with-freetype-dir=/usr
    --enable-gd-native-ttf
    --enable-gd-jis-conv
    --with-openssl
    --with-pdo-mysql
    --with-gettext
    --with-zlib
    --with-bz2
    --with-recode
    --with-mysqli
    --with-readline
    chdir={{ build_dir.path }}/{{ php5_version }}
    creates={{ build_dir.path }}/{{ php5_version }}/Makefile
  tags: php5

- name: Build PHP
  shell: >
    make clean &&
    make
    chdir={{ build_dir.path }}/{{ php5_version }}
    creates={{ build_dir.path }}/{{ php5_version }}/sapi/cli/php
  tags: php5

- name: Install PHP
  command: >
    make install
    chdir={{ build_dir.path }}/{{ php5_version }}
    creates={{ build_dir.path }}/bin/php
  notify:
    - Restart php5_fpm
  tags: php5
